Update serviceinfo-sys-module.md
fido-device-onboard/docs-fidoiot pull request #17
Opened 2021-08-16 08:21 UTC by sharoncornelius

2021-08-17 16:13 UTC, v-vasavi submitted a review, later dismissed

2021-08-19 05:08 UTC, DukeDavis12 commented on docs/implementation-references/serviceinfo-sys-module.md
> +TO2. OwnerServiceInfo message include the isMore and isDone flags.
TO2. OwnerServiceInfo  ==> TO2.OwnerServiceInfo

2021-08-19 05:10 UTC, KiranSukhavasi requested changes
TO2. OwnerServiceInfo no space should be in.

2021-08-19 10:40 UTC, DukeDavis12 commented on docs/implementation-references/serviceinfo-sys-module.md
> +TO2. OwnerServiceInfo message include the isMore and isDone flags.
Fixed.

2021-08-19 10:42 UTC, KiranSukhavasi submitted a review, later dismissed

2021-08-19 10:48 UTC, KiranSukhavasi approved these changes

2021-08-19 10:48 UTC, DukeDavis12 approved these changes

2021-08-19 11:38 UTC, merged